### PR TITLE
Some fixes +  No Space on disk dialog +  Update Game Button

### LINKED ISSUE #228: "appimaged" shows "Invalid desktop file" notification
**Describe the bug**
[appimaged](https://github.com/probonopd/go-appimage) gives "Invalid desktop file" notification when Heroic is launched.

**To Reproduce**
1. Install appimaged
2. Download Heroic AppImage into either $HOME/Applications or $HOME/Downloads
3. Let appimaged detect and integrate Heroic into the system
4. Launch Heroic

**Expected behavior**
No notification

**Desktop (please complete the following information):**
 - Version 1.5.5 (and previous versions [1.4.x, 1.3.x, ...])

**Additional context**
The notification is annoying because it doesn't time-out. I have to close it every time I launch Heroic.

Contents of `.desktop` file generated by `appimaged` is similar to #99.

I also believe bug is related to #128 as the line referenced in #128 is still present in [this file](https://github.com/flavioislima/HeroicGamesLauncher/blob/8d17e4479f5be4a34d2591beec639b1b410278c1/package.json#L37).

### LINKED ISSUE #235: Folder for installation can not be selected
**Describe the bug**
Folder for installation can not be selected, when trying to install a game.

**To Reproduce**
    Try to install a game

    It opens the folderselectiontool.

    No folder can be selected in the end.

**Expected behavior**
Be able to select a folder

**Screenshots**
legendary

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20 Ulyana
-  Game: any
-  Wine/Proton version: wine 5.0

**Additional context**
Using Cinnamon Desktop.
I am also using legendary and reported the bug there, but they said its HeroicGameLauncher related.

### PR DESCRIPTION
**Pull request by flavioislima**
Fix #235 
Fix #228 
Add #233 
Add #156

### CODE REVIEW

**Comment by flavioislima** [comment]
Need translations for:
"Not enough available disk space",
"No Space"
"Update Game"

@onadrog @iWeaker4you @D3SOX @skowr @ianwijma @lol28 @BiRo96 @entaromia

**Comment by D3SOX** [comment]
German:
```json
"Nicht genügend freier Speicherplatz",
"Kein Speicherplatz"
"Spiel aktualisieren"
```

**Comment by BiRo96** [comment]
Hungarian

> "Nincs elég elérhető lemezterület"
> "Nincs hely"
> "Játék Frissítése"

**Comment by ianwijma** [comment]
- Geen ruimte beschikbaar op de harde schijf
- Niet genoeg opslag
- Spel updaten

**Comment by skowr** [comment]
Hi.
Polish:

"Za mało miejsca na dysku",
"Za mało miejsca"
"Aktualizuj grę"

**Comment by entaromia** [comment]
Turkish:

"Yeterli alan mevcut değil",
"Alan Yok"
"Oyunu Güncelle"

**Comment by onadrog** [comment]
FR:

"Espace disque nécessaire insuffisant",
"Pas de place"
"Mettre à jour le jeu"

**Comment by lol28** [comment]
"Недостаточно свободного места на диске",
"Нет места"
"Обновить игру"

Russian

File: electron/main.ts [hunk 1]
```diff
@@ -348,23 +362,29 @@ ipcMain.handle('install', async (event, args) => {
...
+    console.log('finished installing')
+  } catch (error) {
+    const noSpaceMsg = 'Not enough available disk space'
+    const genericMessage = 'installation canceled or had some error'
+    await execAsync(`tail ${logPath} | grep 'disk space'`)
+      .then(({ stdout }) => {
         if (stdout.includes(noSpaceMsg)) {
           console.log(noSpaceMsg)
-          return stdout
+          return showErrorBox(
```
Comment (ianwijma) [inline electron/main.ts:375]: I see this function returns either a string or void (showErrorBox) where the returned value does nothing. Maybe its good to just remove the returns if it isn't being used in the end?

File: electron/main.ts [hunk 2]
```diff
@@ -348,23 +362,29 @@ ipcMain.handle('install', async (event, args) => {
...
         }
-        console.log('installation canceled or had some error')
-      } catch (err) {
-        return err
-      }
-    })
+        console.log(genericMessage)
+        return genericMessage
+      })
+      .catch(() => console.log(genericMessage))
```
Comment (ianwijma) [inline electron/main.ts:386]: Maybe show the error within an error box, so if something goes wrong, the user at least sees that something went wrong.

Comment (ianwijma) [reply electron/main.ts:386]: Also it looks like `genericMessage` is not translated.

File: electron/utils.ts [hunk 3]
```diff
@@ -148,12 +148,32 @@ export const getUserInfo = (): UserInfo => {
...
+              'box.error.diskspace.message',
+              'Not enough available disk space'
+            )
+          )
+        }
+        console.log(genericMessage)
+        return genericMessage
+      })
+      .catch(() => console.log(genericMessage))
+  }
```
Comment (ianwijma) [inline electron/utils.ts:176]: This block of code is VERY similar to the install code ([electron/main.ts:365-387](https://github.com/flavioislima/HeroicGamesLauncher/pull/236/files#diff-13ee644059574b054a4e5ec081666a03579b28da03a50331215908f8d0ef7cfdR365-R387)). Maybe its an idea to unify them for ease of maintainability? Also right now the install and update are in 2 different files which makes it also harder to maintain.

File: src/components/GamePage/GamesSubmenu.tsx [hunk 4]
```diff
@@ -79,6 +86,21 @@ export default function GamesSubmenu({
     return
   }
 
+  async function handleUpdate() {
+    const { response } = await showMessageBox({
+      title: t('box.update.title'),
+      message: t('box.update.message'),
+      buttons: [t('box.yes'), t('box.no')],
+    })
```
Comment (ianwijma) [inline src/components/GamePage/GamesSubmenu.tsx:94]: Do we want to have the fallback language at every translation?

**Review by ianwijma — CHANGES_REQUESTED** [review]
Found some minor issues and one refactor idea.

File: electron/main.ts (hunk 1 above)
Comment (flavioislima) [reply electron/main.ts:375]: Good catch. I'm refactoring it to be more generic as well.

File: electron/main.ts (hunk 2 above)
Comment (flavioislima) [reply electron/main.ts:386]: So, I was about to do that when I realized that this message is being shown everytime the install is canceled, and will be annoying I guess. Because Heroic sends a kill signal to Legendary to stop the installation, and then the exec command will throw an error and then the generic message will be shown. So I'm not sure if this will be good UX wise. 🤔

File: electron/utils.ts (hunk 3 above)
Comment (flavioislima) [reply electron/utils.ts:176]: Yeah, I'll create one single function to avoid repetition

File: src/components/GamePage/GamesSubmenu.tsx (hunk 4 above)
Comment (flavioislima) [reply src/components/GamePage/GamesSubmenu.tsx:94]: The fallback language will always be english, you mean on every key a fallback string? I'm doing this only with new string because then the parser adds the default to all json files and then it is easier to add the translations afterwards.

Comment (ianwijma) [reply src/components/GamePage/GamesSubmenu.tsx:94]: Alrighty! :)

**Review by ianwijma — APPROVED** [review]
Looks awesome =D
